[colors.bright]
black = "0x928374"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xebdbb2"
yellow = "0xfabd2f"

[colors.normal]
black = "0x282828"
blue = "0x458588"
cyan = "0x689d6a"
green = "0x98971a"
magenta = "0xb16286"
red = "0xcc241d"
white = "0xa89984"
yellow = "0xd79921"

[colors.primary]
background = "0x282828"
foreground = "0xebdbb2"

[cursor]
unfocused_hollow = true

[font]
size = 16.0

[font.normal]
family = "Moralerspace Xenon HW"
# family = "HackGen35 Console NF"
# family = "UDEV Gothic 35NF"
# family = "NOTONOTO Console"
style = "Regular"

# [[keyboard.bindings]]
# action = "Paste"
# key = "V"
# mods = "Control|Alt"

# [[keyboard.bindings]]
# action = "Copy"
# key = "C"
# mods = "Control|Alt"

[selection]
save_to_clipboard = true

[window]
dynamic_title = false
title = "Alacritty"
