[[plugins]]
  repo = 'altercation/vim-colors-solarized'
[[plugins]]
  repo = 'basyura/bitly.vim'
[[plugins]]
  repo = 'tyru/open-browser.vim'
[[plugins]]
  repo = 'cohama/vim-hier'
[[plugins]]
  repo = 'dannyob/quickfixstatus'
[[plugins]]
  repo = 'itchyny/lightline.vim'
[[plugins]]
  repo = 'joker1007/vim-markdown-quote-syntax'
[[plugins]]
  repo = 'justinmk/vim-dirvish'
[[plugins]]
  repo = 'Konfekt/FastFold'
[[plugins]]
  repo = 'lambdalisue/vim-unified-diff'
[[plugins]]
  repo = 'Lokaltog/vim-easymotion'
[[plugins]]
  repo = 'ludovicchabant/vim-gutentags'
[[plugins]]
  repo = 'mattn/webapi-vim'
[[plugins]]
  repo = 'nathanaelkane/vim-indent-guides'
[[plugins]]
  repo = 'osyo-manga/shabadou.vim'
[[plugins]]
  repo = 'osyo-manga/vim-watchdogs'
[[plugins]]
  repo = 'rhysd/unite-codic.vim'
[[plugins]]
  repo = 'Shougo/echodoc.vim'
[[plugins]]
  repo = 'Shougo/neocomplete.vim'
[[plugins]]
  repo = 'Shougo/neoinclude.vim'
[[plugins]]
  repo = 'Shougo/neomru.vim'
[[plugins]]
  repo = 'Shougo/neosnippet'
[[plugins]]
  repo = 'Shougo/neosnippet-snippets'
[[plugins]]
  repo = 'Shougo/unite-outline'
[[plugins]]
  repo = 'Shougo/unite.vim'
[[plugins]]
  repo = 'Shougo/vimfiler'
[[plugins]]
  repo = 'Shougo/vimproc.vim'
[[plugins]]
  repo = 'Shougo/vimshell'
[[plugins]]
  repo = 'spolu/dwm.vim'
[[plugins]]
  repo = 'supermomonga/vimshell-kawaii.vim'
[[plugins]]
  repo = 'thinca/vim-quickrun'
[[plugins]]
  repo = 'tpope/vim-fugitive'
[[plugins]]
  repo = 'tpope/vim-surround'
[[plugins]]
  repo = 'tsukkee/unite-tag'
[[plugins]]
  repo = 'tyru/eskk.vim'
[[plugins]]
  repo = 'ujihisa/neco-look'
[[plugins]]
  repo = 'vim-jp/vimdoc-ja'
[[plugins]]
  repo = 'vim-scripts/sh.vim--Cla'
[[plugins]]
  repo = 'Yggdroot/indentLine'
[[plugins]]
  repo = 'yuratomo/w3m.vim'
[[plugins]]
  repo = 'zchee/deoplete-go'
